name: build

env:
  REGISTRY: 'registry.digitalocean.com/edvisor'
  IMAGE_NAME: edvisor-frontend

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${{github.sha}} .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Push image to DigitalOcean
        run: |
          doctl registry login
          docker push $REGISTRY/$IMAGE_NAME:${{github.sha}}
