name: build

env:
  REGISTRY: 'registry.digitalocean.com/edvisor'
  IMAGE_NAME: edvisorru/edvisor-frontend

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build and deploy'
        required: true
        default: 'Mona the Octocat'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: push image to digitalocean
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
