name: build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: cp .env.ci .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_SECRET }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/edvisor/edvisor-frontend:${{ github.sha }}
            registry.digitalocean.com/edvisor/edvisor-frontend:main
          cache-from: type=registry,ref=registry.digitalocean.com/edvisor/edvisor-frontend:main
          cache-to: type=inline
