name: deploy_staging

env:
  REGISTRY: 'registry.digitalocean.com/edvisor'
  IMAGE_NAME: edvisor-frontend

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
